Prevent an easy error in Connect()
BarRaider/obs-websocket-dotnet pull request #52
Opened 2021-02-21 04:02 UTC by Krutonium

Basically if the user of the library forgets to include `ws://` in the url, the library will return a very useless error, specifically

```
Unhandled exception. System.ArgumentException: A relative URI. (Parameter 'url')
```
Which does not help. This prevents that error from ever happening by correcting a forgotten web socket protocol specifier.

It also adds *.idea to the .gitignore, because Rider creates that.

2021-03-18 08:58 UTC, BarRaider requested changes

2021-03-18 08:58 UTC, BarRaider commented on obs-websocket-dotnet/OBSWebsocket.cs
> +            if (url.ToLower().StartsWith("ws://") == false)
Probably more consistant to modify it to:
`if (!url.To....` vs adding a `== false` at the end.

2021-03-18 08:58 UTC, BarRaider commented on obs-websocket-dotnet/OBSWebsocket.cs
> +                url = "ws://" + url;
I would just generate a clear exception vs adding this to the URL.
Something like `new AuthFailureException(@"Invalid server url, must start with 'ws://'");`

2021-03-22 07:45 UTC, Krutonium commented
I made the changes you requested, however I was unable to test them as the .net config on my system is currently quite broken.

2021-05-13 21:43 UTC, Sabuto commented
instead of just removing the exception why not prepend the string with it?

2021-05-13 21:50 UTC, BarRaider commented
Because that's not a forward-looking solution. You should not try to GUESS what the user wants. Especially when we may include options like wss:// in the future.

2021-05-13 22:04 UTC, Sabuto commented
fair point

2021-05-14 22:12 UTC, BarRaider commented
I resolved this by a small tweak to the original PR - thank you!
Resolved in c59bc5f

2021-05-14 22:12 UTC, closed without merging