Virtualcam
BarRaider/obs-websocket-dotnet pull request #63
Opened 2021-07-05 13:53 UTC by TBGRenfold

Based on:

https://github.com/Palakis/obs-websocket/blob/4.9.1/docs/generated/protocol.md#virtual-cam
https://github.com/Palakis/obs-websocket/blob/4.9.1/docs/generated/protocol.md#virtual-cam-1

2021-07-05 14:05 UTC, TBGRenfold commented
Noticed a spelling mistake in this pr.

2021-07-12 21:44 UTC, BarRaider requested changes
Overall looks good, minor tweaks.
Also, please push this to the dev-4.9.1 branch (not Master)

2021-07-12 21:44 UTC, BarRaider commented on obs-websocket-dotnet/OBSWebsocket_Requests.cs
> +            if (width > -1)
please clean up

2021-07-12 21:44 UTC, BarRaider commented on obs-websocket-dotnet/VirtualCamStatus.cs
> +        public VirtualCamStatus(JObject data)
Please also add a default constructor (With no arguments), otherwise this will fail JSON deserialization.

2021-07-12 21:44 UTC, BarRaider commented on obs-websocket-dotnet/OBSWebsocket_Requests.cs
> +        public void StartStopVirtualCam()
Maybe rename to "ToggleVirtualCam" ?

2021-07-13 20:07 UTC, BarRaider commented
Hey,
Was there a reason for commit 443facb "Merge dev-4.9.1 into Virtualcam" given this is being merged into dev-4.9.1?

2021-07-14 07:25 UTC, TBGRenfold commented
> Hey,
> Was there a reason for commit [443facb](https://github.com/BarRaider/obs-websocket-dotnet/commit/443facbb3507ac1fbe42185eb1d78159b296c23c) "Merge dev-4.9.1 into Virtualcam" given this is being merged into dev-4.9.1?
> Other than that it's ready to be merged but didn't understand why that commit was needed.

443facb << Shouldn't of happened. Bit of a PR noob, and realize that I should of made a seperate branch for merging 4.9.1 with any conflicts my end (testing against obs-ws).

2021-07-15 03:08 UTC, merged