Implemented high-volume events, dynamic reidentify, new event protocol
BarRaider/obs-websocket-dotnet pull request #92
Opened 2022-07-28 13:23 UTC by dedmen

Implemented events for protocol v5 ("update-type" changes to "eventType" and event data is in "eventData" member)
Implemented InputVolumeMeters event as a example of a high-volume event that requires dynamic subscription (via Reidentify) for the event

By the way your discord link in readme isn't working.

2022-09-01 09:53 UTC, BarRaider requested changes
Please remove the "_" from variables to align with the existing variable naming conventions in the project.

2022-09-03 15:15 UTC, dedmen commented
Sorry don't have time now to fix the conflicts, maybe tomorrow or next week

2022-10-01 11:33 UTC, dedmen commented
Okey here we go, that should be it.
Tested working.

2022-12-26 18:54 UTC, TabNoc commented
I'm interested in this feature, any updates?

2022-12-28 16:09 UTC, BarRaider commented
I was planning on adding it a while back but there are some uncomplete ("Todo") sections in the identify section that prevented me from pushing it. 
I'll look into taking the Volume parts of the PR and adding that specifically

2023-08-25 11:04 UTC, dblanco215 commented
Hi! I'm trying to implement this feature on my app in C#. I'm add the event subscription but I never receive any data of the volume of OBS. Are there any additional step to can receive this data?

2026-09-13 20:17 UTC, closed without merging